"""User model changes

Revision ID: 0eff46146dfa
Revises: 923574fece9b
Create Date: 2025-09-24 10:49:50.053251

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0eff46146dfa"
down_revision = "923574fece9b"
branch_labels = None
depends_on = None


def upgrade():
    gender_enum = sa.Enum("male", "female", "other", name="genders")
    gender_enum.create(op.get_bind(), checkfirst=True)  # will create only if missing

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birth_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("height", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("weight", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "gender",
                sa.Enum("male", "female", "other", name="genders"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("gender")
        batch_op.drop_column("weight")
        batch_op.drop_column("height")
        batch_op.drop_column("birth_date")

    # ### end Alembic commands ###
