"""add foreign key to template_exercises

Revision ID: 83b18661f576
Revises: dd769ea54453
Create Date: 2025-11-05 19:28:59.216241

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83b18661f576"
down_revision = "dd769ea54453"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    plan_levels = sa.Enum("beginner", "intermediate", "advanced", name="plan_levels")
    plan_levels.create(op.get_bind(), checkfirst=True)  # will create only if missing

    template_muscle_groups = sa.Enum(
        "legs",
        "back",
        "chest",
        "core",
        "calves",
        "arms",
        "shoulders",
        name="template_muscle_groups",
    )
    template_muscle_groups.create(
        op.get_bind(), checkfirst=True
    )  # will create only if missing

    op.create_table(
        "workout_plan_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_plan_id", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_plan_id"],
            ["workout_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_plan_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_day_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_in_workout", sa.Integer(), nullable=False),
        sa.Column("target_sets", sa.Integer(), nullable=False),
        sa.Column("target_reps_min", sa.Integer(), nullable=False),
        sa.Column("target_reps_max", sa.Integer(), nullable=False),
        sa.Column("warmup_sets", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_day_id"],
            ["workout_plan_days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("workout_plan_sessions")
    with op.batch_alter_table("template_exercises", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "muscle_group",
                template_muscle_groups,
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("exercise_number", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("warmup_sets", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("template_exercises_exercise_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("exercise_id")
        batch_op.drop_column("is_warmup")

    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "level",
                plan_levels,
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))

    with op.batch_alter_table("workout_templates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("day_number", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.drop_column("day_of_week")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout_templates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "day_of_week",
                postgresql.ENUM(
                    "mon", "tue", "wed", "thu", "fri", "sat", "sun", name="week_days"
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("description")
        batch_op.drop_column("day_number")

    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.drop_column("is_active")
        batch_op.drop_column("level")

    with op.batch_alter_table("template_exercises", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_warmup", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("exercise_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("template_exercises_exercise_id_fkey"),
            "exercises",
            ["exercise_id"],
            ["id"],
        )
        batch_op.drop_column("warmup_sets")
        batch_op.drop_column("exercise_number")
        batch_op.drop_column("muscle_group")

    op.create_table(
        "workout_plan_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("workout_plan_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "workout_session_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("scheduled_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_plan_id"],
            ["workout_plans.id"],
            name=op.f("workout_plan_sessions_workout_plan_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"],
            ["workout_sessions.id"],
            name=op.f("workout_plan_sessions_workout_session_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("workout_plan_sessions_pkey")),
    )
    op.drop_table("workout_plan_exercises")
    op.drop_table("workout_plan_days")
    # ### end Alembic commands ###
