"""final workout/exercise models

Revision ID: dd769ea54453
Revises: 0eff46146dfa
Create Date: 2025-11-05 16:38:41.185214

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd769ea54453"
down_revision = "0eff46146dfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "level",
            sa.Enum("beginner", "intermediate", "advanced", name="template_levels"),
            nullable=False,
        ),
        sa.Column(
            "day_of_week",
            sa.Enum("mon", "tue", "wed", "thu", "fri", "sat", "sun", name="week_days"),
            nullable=False,
        ),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("is_warmup", sa.Boolean(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("total_performed", sa.Integer(), nullable=False),
        sa.Column("total_weight_lifted", sa.Float(), nullable=False),
        sa.Column("last_performed", sa.Date(), nullable=True),
        sa.Column("is_warmup", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "template_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order_in_workout", sa.Integer(), nullable=False),
        sa.Column("target_sets", sa.Integer(), nullable=False),
        sa.Column("target_reps_min", sa.Integer(), nullable=False),
        sa.Column("target_reps_max", sa.Integer(), nullable=False),
        sa.Column("is_warmup", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["workout_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workout_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.create_index("idx_workout_plan_user", ["user_id"], unique=False)

    op.create_table(
        "workout_plan_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_plan_id", sa.Integer(), nullable=False),
        sa.Column("workout_session_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_plan_id"],
            ["workout_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"],
            ["workout_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exercise_sets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_warmup", sa.Boolean(), nullable=True))

    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workout_plan_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "workout_plans", ["workout_plan_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("workout_plan_id")

    with op.batch_alter_table("exercise_sets", schema=None) as batch_op:
        batch_op.drop_column("is_warmup")

    op.drop_table("workout_plan_sessions")
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.drop_index("idx_workout_plan_user")

    op.drop_table("workout_plans")
    op.drop_table("template_exercises")
    op.drop_table("exercise_statistics")
    op.drop_table("exercise_logs")
    op.drop_table("workout_templates")
    # ### end Alembic commands ###
